In [2]:
# Importing Libraries
import numpy as np
import pandas as pd
import glob

In [3]:
# Loading Files

files = glob.glob("data/*.csv")

In [4]:
# Checking if all the columns name in each table are same

ref_col = list(pd.read_csv(files[0], nrows=0).columns)
for f in files:
    curr_col = list(pd.read_csv(f,nrows=0).columns)
    print(f,"->",curr_col==ref_col)

data\202507-divvy-tripdata.csv -> True
data\202508-divvy-tripdata.csv -> True
data\202509-divvy-tripdata.csv -> True
data\202510-divvy-tripdata.csv -> True
data\202511-divvy-tripdata.csv -> True
data\202512-divvy-tripdata.csv -> True
data\202601-divvy-tripdata.csv -> True
data\202602-divvy-tripdata.csv -> True
data\202603-divvy-tripdata.csv -> True
data\202604-divvy-tripdata.csv -> True
data\202605-divvy-tripdata.csv -> True
data\202606-divvy-tripdata.csv -> True
data\cleaned_trips.csv -> False

In [6]:
# Concat all the tables

df = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)
print(df.shape)

(11859130, 15)

In [17]:
df.describe()

          start_lat     start_lng       end_lat       end_lng
count  5.932349e+06  5.932349e+06  5.926743e+06  5.926743e+06
mean   4.190420e+01 -8.764671e+01  4.190462e+01 -8.764706e+01
std    4.442902e-02  2.711569e-02  4.459233e-02  2.734684e-02
min    4.164850e+01 -8.789000e+01  4.151000e+01 -8.810000e+01
25%    4.188241e+01 -8.766000e+01  4.188275e+01 -8.766000e+01
50%    4.189962e+01 -8.764242e+01  4.190000e+01 -8.764288e+01
75%    4.193000e+01 -8.763000e+01  4.193000e+01 -8.763000e+01
max    4.207000e+01 -8.752000e+01  4.221000e+01 -8.737000e+01

In [20]:
df.sample(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
1092313,AE477E18A5201E8D,classic_bike,2025-08-13 11:35:26.613,2025-08-13 11:39:05.297,Lakeview Ave & Fullerton Pkwy,CHI00469,Clark St & Drummond Pl,CHI00385,41.925858,-87.638973,41.931248,-87.644336,member
2636339,C5EFFB3B3A5D0DA5,classic_bike,2025-10-30 12:12:14.149,2025-10-30 13:17:02.569,Wabash Ave & Cermak Rd,CHI00621,Burnham Harbor,CHI00558,41.852619,-87.626488,41.857412,-87.613792,casual
132609,6237F852EA089DA9,classic_bike,2025-07-15 07:29:48.939,2025-07-15 07:35:31.950,Clark St & Elm St,CHI00281,LaSalle St & Illinois St,CHI00358,41.902970,-87.631300,41.890762,-87.631697,member
1107129,12D340DF9AF782E6,classic_bike,2025-08-31 16:28:40.337,2025-08-31 16:33:25.731,Ellis Ave & 53rd St,CHI00585,University Ave & 57th St,CHI00551,41.799336,-87.600958,41.791478,-87.599861,member
5206515,B7F552E3BAD76B16,classic_bike,2026-06-12 18:40:02.467,2026-06-12 19:11:01.268,Navy Pier,CHI01747,Navy Pier,CHI01747,41.892278,-87.612043,41.892278,-87.612043,casual

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5932349 entries, 0 to 5932348
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 588.4+ MB

In [15]:
# Converting datatype to datetime

df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11859130 entries, 0 to 11859129
Data columns (total 15 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
 13  ride_length_min     float64
 14  day_of_week         object
dtypes: datetime64[ns](2), float64(5), object(8)
memory usage: 1.3+ GB

In [17]:
df['member_casual'].value_counts()

member_casual
member    7630385
casual    4228745
Name: count, dtype: int64

In [18]:
# New column : Ride length minutes

df['ride_length_min'] = (df['ended_at'] - df['started_at']).dt.total_seconds()/60

In [19]:
df['ride_length_min'].describe()

count    1.185913e+07
mean     1.507727e+01
std      4.281087e+01
min     -5.479480e+01
25%      5.357583e+00
50%      9.363750e+00
75%      1.645505e+01
max      1.559950e+03
Name: ride_length_min, dtype: float64

In [20]:
print("minimum ride in minutes : ", df['ride_length_min'].min(), "\nmaximum ride in hours : ",
df['ride_length_min'].max()/60)

minimum ride in minutes :  -54.7948
maximum ride in hours :  25.999169722222224

In [21]:
# Removing ride that whose length time is less then 0 and greater then 24 hrs

df_cleaned = df[df['ride_length_min'] > 0]

In [22]:
df_cleaned = df_cleaned[df_cleaned['ride_length_min'] <= 1440]

In [23]:
print("minimum ride in minutes : ", df_cleaned['ride_length_min'].min(), "\nmaximum ride in hours : ",
df_cleaned['ride_length_min'].max()/60)

minimum ride in minutes :  0.0007666666666666667
maximum ride in hours :  23.999599166666666

In [26]:
# Creating a column that shows day name

df_cleaned['day_of_week']= df_cleaned['started_at'].dt.day_name()

In [27]:
df_cleaned[['started_at', 'day_of_week']].sample(10)

                      started_at day_of_week
4888862  2026-05-02 18:13:52.032    Saturday
908413   2025-08-14 12:29:22.905    Thursday
11047924 2026-05-08 17:35:29.128      Friday
4437506  2026-04-11 16:33:46.832    Saturday
11700597 2026-06-08 16:19:19.854      Monday
5090980  2026-05-26 18:36:23.378     Tuesday
10196239 2026-04-22 18:03:37.791   Wednesday
770788   2025-08-21 15:39:07.070    Thursday
6336196  2025-07-18 15:47:24.227      Friday
3983700  2026-03-30 07:19:18.515      Monday

In [12]:

# Checkpoint

df_cleaned.to_csv('data/cleaned_trips.csv',index = False)

In [28]:
df_cleaned = pd.read_csv('data/cleaned_trips.csv')

In [29]:
df_cleaned['member_casual'].value_counts()

member_casual
member    3814670
casual    2112111
Name: count, dtype: int64

In [30]:
df_cleaned.groupby('member_casual')['ride_length_min'].mean()

member_casual
casual    18.570856
member    12.065629
Name: ride_length_min, dtype: float64

In [31]:
df_cleaned.groupby(['member_casual', 'day_of_week'])['ride_id'].count()

member_casual  day_of_week
casual         Friday         330712
               Monday         245285
               Saturday       445387
               Sunday         347161
               Thursday       264033
               Tuesday        244497
               Wednesday      235036
member         Friday         559810
               Monday         535526
               Saturday       483443
               Sunday         405821
               Thursday       608944
               Tuesday        618675
               Wednesday      602451
Name: ride_id, dtype: int64

In [32]:
df_cleaned['started_at'] = pd.to_datetime(df_cleaned['started_at'])
df_cleaned['ended_at'] = pd.to_datetime(df_cleaned['ended_at'])


df_cleaned['month'] = df_cleaned['started_at'].dt.month_name()

In [33]:
df_cleaned.groupby(['member_casual', 'month'])['ride_id'].count()

member_casual  month
casual         April        131231
               August       337246
               December      28005
               February      41088
               January       24656
               July         322505
               June         307883
               March         87631
               May          244654
               November      98871
               October      223569
               September    264772
member         April        316695
               August       452355
               December     112415
               February     160251
               January      112933
               July         439965
               June         454010
               March        229121
               May          408510
               November     257292
               October      421921
               September    449202
Name: ride_id, dtype: int64

In [34]:
df_cleaned.groupby(['member_casual', 'rideable_type'])['ride_id'].count()

member_casual  rideable_type
casual         classic_bike      630410
               electric_bike    1481701
member         classic_bike     1283911
               electric_bike    2530759
Name: ride_id, dtype: int64

In [35]:
pd.crosstab(df_cleaned['member_casual'], df_cleaned['rideable_type'], normalize='index') * 100

rideable_type  classic_bike  electric_bike
member_casual
casual            29.847390      70.152610
member            33.657197      66.342803

In [36]:
# summary by day 


day_summary = df_cleaned.groupby(['member_casual', 'day_of_week']).agg(
    ride_count=('ride_id', 'count'),
    avg_ride_length=('ride_length_min', 'mean')
).reset_index()

print(day_summary)

   member_casual day_of_week  ride_count  avg_ride_length
0         casual      Friday      330712        18.242277
1         casual      Monday      245285        18.571482
2         casual    Saturday      445387        20.970054
3         casual      Sunday      347161        21.588672
4         casual    Thursday      264033        16.118552
5         casual     Tuesday      244497        16.102853
6         casual   Wednesday      235036        15.350839
7         member      Friday      559810        12.025981
8         member      Monday      535526        11.786253
9         member    Saturday      483443        13.245205
10        member      Sunday      405821        13.242639
11        member    Thursday      608944        11.610269
12        member     Tuesday      618675        11.619988
13        member   Wednesday      602451        11.529305

In [37]:
day_summary.to_csv('data/summary_by_day.csv', index=False)

In [38]:
# summary by month


month_summary = df_cleaned.groupby(['member_casual', 'month']).agg(
    ride_count=('ride_id', 'count'),
    avg_ride_length=('ride_length_min', 'mean')
).reset_index()

month_summary.to_csv('data/summary_by_month.csv', index=False)

In [ ]:
# summary by bike type


bike_summary = df_cleaned.groupby(['member_casual', 'rideable_type']).agg(
    ride_count=('ride_id', 'count')
).reset_index()

bike_summary.to_csv('data/summary_by_bike_type.csv', index=False)

In [39]:
df_cleaned['hour'] = df_cleaned['started_at'].dt.hour

In [40]:
df_cleaned = pd.read_csv('data/cleaned_trips.csv', parse_dates=['started_at', 'ended_at'])

In [41]:
df_cleaned['hour'] = df_cleaned['started_at'].dt.hour

In [ ]:
# summary by hour


hour_summary = df_cleaned.groupby(['member_casual', 'hour']).agg(
    ride_count=('ride_id', 'count')
).reset_index()

hour_summary['rank_within_group'] = hour_summary.groupby('member_casual')['ride_count'].rank(ascending=False, method='min')

hour_summary.to_csv('data/summary_by_hour.csv', index=False)

In [43]:
# summary by avg length


avg_length_summary = df_cleaned.groupby('member_casual').agg(
    avg_ride_length=('ride_length_min', 'mean')
).reset_index()

avg_length_summary.to_csv('data/summary_avg_length.csv', index=False)